services:
  api:
    image: api:latest
    build:
      context: .
    ports:
      - "8000:8000"
    command:
      [
        "uvicorn",
        "app.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
        "--reload",
      ]
